version: '3.4'
services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - starbank-network

  user-api:
    image: nelsonssoares/user-api
    restart: always
    build: ./user-api
    working_dir: /user-api

    environment:
      TZ: America=Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql:3306/mydb
      SPRING.DATASOUCE.USERNAME: root
      SPRING.DATASOUCE.PASSWORD: 123456
    command: mvn spring-boot:run

    depends_on:
      - mysql

networks:
  starbank-network:
    driver: bridge