version: '3.4'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    ports:
      - "3308:3308"
    networks:
      - starbank-network

  eureka-server:
    image: nelsonssoares/eureka-server
    build: ./Eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - starbank-network

  user-api:
    image: nelsonssoares/userapi
    build: ./userapi
    container_name: userapi
    volumes:
      - ./userapi/files/uploads:/app/files/uploads
      - ./userapi/files/downloads:/app/files/downloads
    environment:
      TZ: America/Sao_Paulo
      EMAIL_USERNAME: shadowdarkside2@gmail.com
      EMAIL_PASSWORD: pnry ydzo tebr amkq
      EMAIL_FROM: shadowdarkside2@gmail.com
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - mysql
      - eureka-server
    networks:
      - starbank-network

  authentication-gateway:
    image: nelsonssoares/authentication-gateway
    build: ./Authentication-Gateway
    container_name: authentication-gateway
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - starbank-network

networks:
  starbank-network:
    driver: bridge
