package com.github.nelsonssoares.userapi.commons.constants.enums;

public enum Countries {
    AFEGANISTAO("Afeganistão", "+93", "Ásia"),
    AFRICA_DO_SUL("África do Sul", "+27", "África"),
    ALBANIA("Albânia", "+355", "Europa"),
    ALEMANHA("Alemanha", "+49", "Europa"),
    ANDORRA("Andorra", "+376", "Europa"),
    ANGOLA("Angola", "+244", "África"),
    ANTIGUA_E_BARBUDA("Antígua e Barbuda", "+1", "Américas"),
    ARABIA_SAUDITA("Arábia Saudita", "+966", "Ásia"),
    ARGELIA("Argélia", "+213", "África"),
    ARGENTINA("Argentina", "+54", "Américas"),
    ARMENIA("Armênia", "+374", "Ásia"),
    AUSTRALIA("Austrália", "+61", "Oceania"),
    AUSTRIA("Áustria", "+43", "Europa"),
    AZERBAIJAO("Azerbaijão", "+994", "Ásia"),
    BAHAMAS("Bahamas", "+1", "Américas"),
    BAHREIN("Bahrein", "+973", "Ásia"),
    BANGLADESH("Bangladesh", "+880", "Ásia"),
    BARBADOS("Barbados", "+1", "Américas"),
    BELGICA("Bélgica", "+32", "Europa"),
    BELIZE("Belize", "+501", "Américas"),
    BENIN("Benin", "+229", "África"),
    BIELORUSSIA("Bielorrússia", "+375", "Europa"),
    BOLIVIA("Bolívia", "+591", "Américas"),
    BOSNIA_HERZEGOVINA("Bósnia e Herzegovina", "+387", "Europa"),
    BOTSUANA("Botsuana", "+267", "África"),
    BRASIL("Brasil", "+55", "Américas"),
    BRUNEI("Brunei", "+673", "Ásia"),
    BULGARIA("Bulgária", "+359", "Europa"),
    BURKINA_FASO("Burkina Faso", "+226", "África"),
    BURUNDI("Burundi", "+257", "África"),
    BUTAO("Butão", "+975", "Ásia"),
    CABO_VERDE("Cabo Verde", "+238", "África"),
    CAMAROES("Camarões", "+237", "África"),
    CAMBOJA("Camboja", "+855", "Ásia"),
    CANADA("Canadá", "+1", "Américas"),
    CATAR("Catar", "+974", "Ásia"),
    CAZAQUISTAO("Cazaquistão", "+7", "Ásia"),
    CHADE("Chade", "+235", "África"),
    CHILE("Chile", "+56", "Américas"),
    CHINA("China", "+86", "Ásia"),
    CHIPRE("Chipre", "+357", "Europa"),
    COLOMBIA("Colômbia", "+57", "Américas"),
    COMORES("Comores", "+269", "África"),
    COREIA_DO_NORTE("Coreia do Norte", "+850", "Ásia"),
    COREIA_DO_SUL("Coreia do Sul", "+82", "Ásia"),
    COSTA_DO_MARFIM("Costa do Marfim", "+225", "África"),
    COSTA_RICA("Costa Rica", "+506", "Américas"),
    CROACIA("Croácia", "+385", "Europa"),
    CUBA("Cuba", "+53", "Américas"),
    DINAMARCA("Dinamarca", "+45", "Europa"),
    DJIBUTI("Djibuti", "+253", "África"),
    DOMINICA("Dominica", "+1", "Américas"),
    EGITO("Egito", "+20", "África"),
    EMIRADOS_ARABES_UNIDOS("Emirados Árabes Unidos", "+971", "Ásia"),
    EQUADOR("Equador", "+593", "Américas"),
    ERITREIA("Eritreia", "+291", "África"),
    ESLOVAQUIA("Eslováquia", "+421", "Europa"),
    ESLOVENIA("Eslovênia", "+386", "Europa"),
    ESPANHA("Espanha", "+34", "Europa"),
    ESTADOS_UNIDOS("Estados Unidos", "+1", "Américas"),
    ESTONIA("Estônia", "+372", "Europa"),
    ETIOPIA("Etiópia", "+251", "África"),
    FIJI("Fiji", "+679", "Oceania"),
    FILIPINAS("Filipinas", "+63", "Ásia"),
    FINLANDIA("Finlândia", "+358", "Europa"),
    FRANCA("França", "+33", "Europa"),
    GABAO("Gabão", "+241", "África"),
    GAMBIA("Gâmbia", "+220", "África"),
    GANA("Gana", "+233", "África"),
    GEORGIA("Geórgia", "+995", "Ásia"),
    GRANADA("Granada", "+1", "Américas"),
    GRECIA("Grécia", "+30", "Europa"),
    GUATEMALA("Guatemala", "+502", "Américas"),
    GUIANA("Guiana", "+592", "Américas"),
    GUINE("Guiné", "+224", "África"),
    GUINE_BISSAU("Guiné-Bissau", "+245", "África"),
    GUINE_EQUATORIAL("Guiné Equatorial", "+240", "África"),
    HAITI("Haiti", "+509", "Américas"),
    HOLANDA("Holanda", "+31", "Europa"),
    HONDURAS("Honduras", "+504", "Américas"),
    HUNGRIA("Hungria", "+36", "Europa"),
    IEMEN("Iêmen", "+967", "Ásia"),
    ILHAS_MARSHALL("Ilhas Marshall", "+692", "Oceania"),
    ILHAS_SALOMAO("Ilhas Salomão", "+677", "Oceania"),
    INDIA("Índia", "+91", "Ásia"),
    INDONESIA("Indonésia", "+62", "Ásia"),
    IRA("Irã", "+98", "Ásia"),
    IRAQUE("Iraque", "+964", "Ásia"),
    IRLANDA("Irlanda", "+353", "Europa"),
    ISLANDIA("Islândia", "+354", "Europa"),
    ISRAEL("Israel", "+972", "Ásia"),
    ITALIA("Itália", "+39", "Europa"),
    JAMAICA("Jamaica", "+1", "Américas"),
    JAPAO("Japão", "+81", "Ásia"),
    JORDANIA("Jordânia", "+962", "Ásia"),
    KIRIBATI("Kiribati", "+686", "Oceania"),
    KOSOVO("Kosovo", "+383", "Europa"),
    KUWAIT("Kuwait", "+965", "Ásia"),
    LAOS("Laos", "+856", "Ásia"),
    LESOTO("Lesoto", "+266", "África"),
    LETONIA("Letônia", "+371", "Europa"),
    LIBANO("Líbano", "+961", "Ásia"),
    LIBERIA("Libéria", "+231", "África"),
    LIBIA("Líbia", "+218", "África"),
    LIECHTENSTEIN("Liechtenstein", "+423", "Europa"),
    LITUANIA("Lituânia", "+370", "Europa"),
    LUXEMBURGO("Luxemburgo", "+352", "Europa"),
    MACEDONIA_DO_NORTE("Macedônia do Norte", "+389", "Europa"),
    MADAGASCAR("Madagascar", "+261", "África"),
    MALASIA("Malásia", "+60", "Ásia"),
    MALAVI("Malawi", "+265", "África"),
    MALDIVAS("Maldivas", "+960", "Ásia"),
    MALI("Mali", "+223", "África"),
    MALTA("Malta", "+356", "Europa"),
    MARROCOS("Marrocos", "+212", "África"),
    MAURICIA("Maurícia", "+230", "África"),
    MAURITANIA("Mauritânia", "+222", "África"),
    MEXICO("México", "+52", "Américas"),
    MICRONESIA("Micronésia", "+691", "Oceania"),
    MOCAMBIQUE("Moçambique", "+258", "África"),
    MOLDOVA("Moldova", "+373", "Europa"),
    MONACO("Mônaco", "+377", "Europa"),
    MONGOLIA("Mongólia", "+976", "Ásia"),
    MONTENEGRO("Montenegro", "+382", "Europa"),
    NAMIBIA("Namíbia", "+264", "África"),
    NAURU("Nauru", "+674", "Oceania"),
    NEPAL("Nepal", "+977", "Ásia"),
    NICARAGUA("Nicarágua", "+505", "Américas"),
    NIGER("Níger", "+227", "África"),
    NIGERIA("Nigéria", "+234", "África"),
    NORUEGA("Noruega", "+47", "Europa"),
    NOVA_ZELANDIA("Nova Zelândia", "+64", "Oceania"),
    OMA("Omã", "+968", "Ásia"),
    PALAU("Palau", "+680", "Oceania"),
    PALESTINA("Palestina", "+970", "Ásia"),
    PANAMA("Panamá", "+507", "Américas"),
    PAPUA_NOVA_GUINE("Papua-Nova Guiné", "+675", "Oceania"),
    PAQUISTAO("Paquistão", "+92", "Ásia"),
    PARAGUAI("Paraguai", "+595", "Américas"),
    PERU("Peru", "+51", "Américas"),
    POLONIA("Polônia", "+48", "Europa"),
    PORTUGAL("Portugal", "+351", "Europa"),
    QUIRGUISTAO("Quirguistão", "+996", "Ásia"),
    QUIRIBATI("Quiribati", "+686", "Oceania"),
    REINO_UNIDO("Reino Unido", "+44", "Europa"),
    REPUBLICA_CENTRO_AFRICANA("República Centro-Africana", "+236", "África"),
    REPUBLICA_CHECA("República Tcheca", "+420", "Europa"),
    REPUBLICA_DOMINICANA("República Dominicana", "+1", "Américas"),
    ROMENIA("Romênia", "+40", "Europa"),
    RUANDA("Ruanda", "+250", "África"),
    RUSSIA("Rússia", "+7", "Europa/Ásia"),
    SAMOA("Samoa", "+685", "Oceania"),
    SANTA_LUCIA("Santa Lúcia", "+1", "Américas"),
    SAO_CRISTOVAO_E_NEVIS("São Cristóvão e Nevis", "+1", "Américas"),
    SAO_MARINO("São Marino", "+378", "Europa"),
    SAO_TOME_E_PRINCIPE("São Tomé e Príncipe", "+239", "África"),
    SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas", "+1", "Américas"),
    SEICHELES("Seicheles", "+248", "África"),
    SENEGAL("Senegal", "+221", "África"),
    SERRA_LEOA("Serra Leoa", "+232", "África"),
    SERVIA("Sérvia", "+381", "Europa"),
    SINGAPURA("Singapura", "+65", "Ásia"),
    SIRIA("Síria", "+963", "Ásia"),
    SOMALIA("Somália", "+252", "África"),
    SRI_LANKA("Sri Lanka", "+94", "Ásia"),
    SUDAO("Sudão", "+249", "África"),
    SUDAO_DO_SUL("Sudão do Sul", "+211", "África"),
    SUECIA("Suécia", "+46", "Europa"),
    SUICA("Suíça", "+41", "Europa"),
    SURINAME("Suriname", "+597", "Américas"),
    TAILANDIA("Tailândia", "+66", "Ásia"),
    TAJIQUISTAO("Tajiquistão", "+992", "Ásia"),
    TANZANIA("Tanzânia", "+255", "África"),
    TIMOR_LESTE("Timor-Leste", "+670", "Ásia"),
    TOGO("Togo", "+228", "África"),
    TONGA("Tonga", "+676", "Oceania"),
    TRINIDAD_E_TOBAGO("Trinidad e Tobago", "+1", "Américas"),
    TUNISIA("Tunísia", "+216", "África"),
    TURCOMENISTAO("Turcomenistão", "+993", "Ásia"),
    TURQUIA("Turquia", "+90", "Ásia/Europa"),
    TUVALU("Tuvalu", "+688", "Oceania"),
    UCRANIA("Ucrânia", "+380", "Europa"),
    UGANDA("Uganda", "+256", "África"),
    URUGUAI("Uruguai", "+598", "Américas"),
    UZBEQUISTAO("Uzbequistão", "+998", "Ásia"),
    VANUATU("Vanuatu", "+678", "Oceania"),
    VATICANO("Vaticano", "+379", "Europa"),
    VENEZUELA("Venezuela", "+58", "Américas"),
    VIETNA("Vietnã", "+84", "Ásia"),
    ZAMBIA("Zâmbia", "+260", "África"),
    ZIMBABUE("Zimbábue", "+263", "África");

    private final String nome;
    private final String ddi;
    private final String continente;

    Countries(String nome, String ddi, String continente) {
        this.nome = nome;
        this.ddi = ddi;
        this.continente = continente;
    }

    public String getNome() {
        return nome;
    }

    public String getDdi() {
        return ddi;
    }

    public String getContinente() {
        return continente;
    }
}
