feign:
  user-api:
    name: user-api
    url: http://localhost:8765/starbank/users
cors:
  originsPatterns: http://localhost:8080 , http://localhost:4200
server:
  port: 8765
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: Authentication-Gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-api
            uri: lb://user-api
            predicates:
              - Path=/starbank/users/**
