## Configuração do Eureka Client
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka


# Configuração para upload e download de arquivos

file:
  upload-dir: /app/files/uploads
  download-dir: /app/files/downloads
  max-file-size: 200MB
  max-request-size: 215MB

  #Configuração de CORS
cors:
  originsPatterns: http://localhost:8080 , http://localhost:4200

spring:
  mail:
    subject: "Default Subject"
    message: "Default Message"
    host: smtp.gmail.com
    port: 587
  #    username: shadowdarkside2@gmail.com
  #    password: pnry ydzo tebr amkq
  #    from: shadowdarkside2@gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    from: ${EMAIL_FROM}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    # Configuração para download e upload do arquivo
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 200MB
      max-request-size: 215MB
  application:
    name: user-api
  profiles:
    active: dev
  cloud:
    discovery:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    password: '123456'
    username: root
    url: jdbc:mysql://mysql:3306/mydb
server:
  error:
    include-stacktrace: never
    include-exception: 'false'
  port: ${PORT:0} #8080
