name: Continuous Integration and Delivery with GitHub Actions

on:
  push:
    branches: [ "master" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0 
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: mydb
        ports:
          - 3306:3306

    steps:
      - name: Login to docker hub
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build Application Authentication-Gateway.jar
        working-directory: ./Authentication-Gateway
        run: mvn clean package

      - name: Build Application Eureka-server.jar
        working-directory: ./Eureka-server
        run: mvn clean package

      - name: Build Application userapi.jar
        working-directory: ./userapi
        run: mvn clean package

      - name: Docker Compose Build 
        working-directory: ./
        run: docker compose build

      - name: Push to DockerHub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/userapi:latest ${{ secrets.DOCKER_USERNAME }}/userapi:ghjid

          docker push ${{ secrets.DOCKER_USERNAME }}/userapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/authentication-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/userapi:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/authentication-gateway:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-server:${{ github.run_id }}
